# Generated by Django 5.2.2 on 2025-06-07 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Budgets', to='Etudiants.etudiant')),
            ],
            options={
                'ordering': ['-mois'],
                'unique_together': {('etudiant', 'mois')},
            },
        ),
    ]
